name: My CI Pipeline
on:
  push:
    branches:  'v[0-9]*\.[0-9]*'


jobs:
  build:
    if: ${{ startsWith(github.event.head_commit.message, '#NORUN') == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my code
        uses: actions/checkout@v3


      - name: Run Scanner
        id: scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-ref: '.'
          scan-type: 'fs'
          exit-code: '1'
          format: 'table'
          output: 'err.txt'
          severity: ${{ vars.SEVERITY }}


      - name: Failed scanner
        if: always() &&  (steps.scanner.outcome == 'failure')
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: 'scanner Failed'
          SLACK_WEBHOOK: ${{ secrets.SLACK_TEST_HOOK }}
          

      - name: Upload err.txt
        if: always() && (steps.scanner.outcome == 'failure')
        uses: adrey/slack-file-upload-action@master
        with:
          channel: test
          path: err.txt
          token: ${{ secrets.SLACK_BOT_TOKEN }}


      - name: Upload err.txt
        if: always() && (steps.scanner.outcome == 'failure')
        uses: adrey/slack-file-upload-action@master
        with:
          channel: test
          path: err.txt
          token: ${{ secrets.SLACK_BOT_TOKEN }}


      - name: Build Image
        run: |
          docker build -t ryelgl/fortune:${{ github.sha }} .
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: 'v2.2.0' 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Build and Push
        id: buildpush
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ryelgl/fortune:${{ github.sha }}


      - name: Sign fortune image
        run: |
          echo "$PRIVATE_KEY" > cosign.key
          cosign sign --verbose --yes --key cosign.key "${TAGS}@${DIGEST}"
        env:
          TAGS: "ryelgl/fortune"
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.buildpush.outputs.digest }}


      - name: Success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: |
            *Name*: Li GengLai
            *MatriculationNumber*: A0285973J
            *Email*: RYELG177@gmail.com
            *Repository* :${{ github.server_url }}/${{ github.repository }}
            *DockerHubURL*: https://hub.docker.com/repository/docker/ryelgl/fortune/general
          SLACK_WEBHOOK: ${{ secrets.SLACK_TEST_HOOK }}
